### ISSUE TITLE
C# Documentation

### ISSUE THREAD

**Issue by DeividReinkeSchiitz** [Natalnet/relex#6]
I started using sBotics, and the program uses the R-educ language, however, it is not a common language for programming. So, I'm thinking of using C # (or any other), but I'm not finding any reference to the documentation. 
Is there an alternative programming language in R-educ, with documentation?

![C#Github](https://user-images.githubusercontent.com/55961826/86315112-aa832f00-bbff-11ea-881d-2def3f8ca1c0.png)

**Comment by joaodalino** [comment]
Im having the same issue, i speak portuguese but i did not understand that language is kind of strange for we that already know a programming language.

**Comment by victor-torres** [comment]
Hey, thank you for submitting this issue. 

The R-Educ language was indeed designed with a focus on beginner programmers. A major use-case indeed involves people that have never had contact with robots nor programming languages. It really shines when adopted in robotics courses for children and teenagers, for example. If you are more experienced with programming languages then it makes total sense to use something more advanced such as C#.

I was involved with the development of R-Educ and W-Educ (its programming environment) in the past, but I'm out of date regarding its current status. All I can say is that this sBotics is related to the W-Educ platform so you might find better support there on its own repository: https://github.com/Natalnet/weduc. It's indeed lacking documentation for this tool and the webpage doesn't say much about how it should be used so I suggest you open another issue there so it get more visibility in the right place.

Also, if you're interested in the R-Educ language, here you can find a simple tutorial/documentation of this language in the Wiki of an old version of the  W-Educ environment (Brazilian Portuguese): https://github.com/Natalnet/W-Educ/wiki/Tutorial-da-Linguagem-R-Educ and https://github.com/Natalnet/W-Educ/wiki/Programas-B%C3%A1sicos

**Comment by DeividReinkeSchiitz** [comment]
Thank for your answer Victor, it helped me a lot! I'll try to open a new issue in https://github.com/Natalnet/weduc as you recommended me.

**Comment by almeidafranci** [comment]
Hi @DeividReinkeSchiitz and @MrFalcon. Thanks for reaching out and sorry for the late reply.
Indeed what @victor-torres said about the purpose of the language is true. We're working on tools to make it more friendly to those who already have some knowledge of programming.
Regarding its use with sBotics, our team at Weduc and sBotics is preparing an update so you can more clearly see the equivalence of R-Educ functions and C# code.
As this repo is focused exclusively on the R-Educ language itself, I'll be closing your issue. Please feel free to contact us regarding sBotics and C# via the lower-left support button on your sBotics screen.
